import 'package:get/get.dart';

import '../models/home_models/product.dart';

class HomeController extends GetxController {
  RxList<Product> listProductNew = [
    Product(
      id: 0,
      image: 'assets/images/product.png',
      name: 'T-Shirt SPANISH',
      star: 4,
      evaluate: 10,
      typeProduct: 'Mango',
      price: 9,
      isNew: true,
      isOutOfStock: false,
    ),
    Product(
      id: 1,
      image: 'assets/images/product-2.png',
      name: 'Sport Dress',
      star: 5,
      evaluate: 1,
      typeProduct: 'Sitlly',
      price: 22,
      salePrice: 19,
      isOutOfStock: true,
    ),
    Product(
      id: 2,
      image: 'assets/images/product-3.png',
      name: 'Sport',
      star: 5,
      evaluate: 5,
      typeProduct: 'Dorothy',
      price: 14,
      salePrice: 10,
      isNew: true,
      percent: 12,
      isOutOfStock: false,
    ),
    Product(
      id: 2,
      image: 'assets/images/product-4.png',
      name: 'Light blouse',
      star: 0,
      evaluate: 0,
      typeProduct: 'Dorothy Perkins',
      price: 14,
      isNew: true,
      isOutOfStock: false,
    ),
    Product(
      id: 2,
      image: 'assets/images/product-5.png',
      name: 'Pullover',
      star: 5,
      evaluate: 5,
      typeProduct: 'Mango',
      price: 14,
      salePrice: 10,
      percent: 12,
      isOutOfStock: false,
    ),
    Product(
      id: 2,
      image: 'assets/images/product-6.png',
      name: 'Shirt',
      star: 4,
      evaluate: 3,
      typeProduct: 'Topshop',
      price: 51,
      isOutOfStock: false,
    ),
  ].obs;
}
